@baseUrl = http://localhost:8000

### Health Check Endpoint
GET {{baseUrl}}/health

### User Registration Endpoint
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John",
  "email": "testee@teste.com.br",
  "password": "super123456"
}
